Task/at 25 pontos
pietro1704/challengeFinal pull request #24
Opened 2020-10-24 01:05 UTC by igdutra

2020-10-26 23:29 UTC, pietro1704 commented on .swiftlint.yml
> +disabled_rules: # rule identifiers to exclude from running
vai dar push no swiftlint mesmo??
perguntando de boa

2020-10-26 23:29 UTC, pietro1704 commented on Podfile.lock
> +COCOAPODS: 1.10.0
vai dar push no .lock?

2020-10-26 23:30 UTC, pietro1704 commented on challengeFinal/App-SceneDelegate/AppDelegate.swift
> +
isso fica aqui pra config inicial do app? Tem que ficar aqui mesmo?

2020-10-26 23:32 UTC, pietro1704 commented on challengeFinalComponents/ChoiceView/ChoiceView.swift
STONKS

2020-10-26 23:33 UTC, pietro1704 reviewed
da uma revisada nos comentários, ma se eu estiver errado tranquilo. @guilhermeluisdomingues  e @guilhermeShima deem uma olhada tambem

2020-10-27 10:55 UTC, igdutra commented on .swiftlint.yml
> +disabled_rules: # rule identifiers to exclude from running
O push do swiftlint é só esse conjunto de regras, só esse arquivo .yml. Ai como você tem Swiftlint instalado no terminal, ele vai rodar automaticamente no projeto ;) o que tinha de configuração no arquivo proj tb já fiz. É só um script no Build phases.

2020-10-27 10:56 UTC, igdutra commented on Podfile.lock
> +COCOAPODS: 1.10.0
ótima pergunta! hahaha não vi que tinha mudado, só tinha dado pod update e ai aconteceu isso. Mt ruim se mandar? @guilhermeShima

2020-10-27 11:00 UTC, igdutra commented on challengeFinal/App-SceneDelegate/AppDelegate.swift
> +
Então, ideia era passar o PlayerService como injeção de dependência. Concordo com você que instancia no AppDelegate não é mt bonito, mas como precisaria no coordinator ai não pensei em uma alternativa..

2020-10-27 11:00 UTC, igdutra commented on challengeFinalComponents/ChoiceView/ChoiceView.swift
não entendi hahaha

2020-10-27 11:53 UTC, guilhermeShima requested changes
Nice job!

2020-10-27 11:53 UTC, guilhermeShima commented on Podfile.lock
> +COCOAPODS: 1.10.0
<img width="1081" alt="Screen Shot 2020-10-27 at 08 36 02" src="https://user-images.githubusercontent.com/25368628/97296453-74615f00-182f-11eb-9f39-3b78167a7cf5.png">

O pod lock é onde as versões dos pods e do próprio cocoapod é "travado", fique atento quanto a isso, afinal se atualizado todos do time precisam atualizar.

2020-10-27 11:53 UTC, guilhermeShima commented on challengeFinal/App-SceneDelegate/AppDelegate.swift
> +
Voce pode instanciar o service nos Coordinators e passar para o ViewModel!

2020-10-27 11:53 UTC, guilhermeShima commented on challengeFinal/Flow/Chapter/Coordinator/ChapterCoordinator.swift
> +        let viewModel = ChapterViewModel(node: storyNode, coordinatorDelegate: self, playerService: playerService)
Você pode criar o Service aqui no start!

2020-10-27 11:53 UTC, guilhermeShima commented on challengeFinal/Flow/Story/Coordinator/StoryCoordinator.swift
> +        playerService.saveChoosenNode(id: storyNode.id)
Você consegue chamar essa função no view model?

2020-10-27 11:55 UTC, guilhermeluisdomingues approved these changes
nice!

2020-10-27 11:55 UTC, guilhermeluisdomingues commented on challengeFinal/App-SceneDelegate/AppDelegate.swift
> +
Nesse ponto aqui, no futuro, vamos chamar o MainCoordinator e a partir de lá instanciaremos os demais..

2020-10-27 14:42 UTC, guilhermeShima approved these changes

2020-10-27 22:46 UTC, merged