Only random if user get 0 points
pietro1704/challengeFinal pull request #52
Opened 2020-11-25 15:08 UTC by guilhermeluisdomingues

2020-11-25 16:16 UTC, guilhermeShima requested changes

2020-11-25 16:16 UTC, guilhermeShima commented on challengeFinal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = BAB5K2DF2B;
Remove your development team!

2020-11-25 16:16 UTC, guilhermeShima commented on challengeFinal.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = BAB5K2DF2B;
Remove your development team!

2020-11-25 16:16 UTC, guilhermeShima commented on challengeFinal/Flow/Story/Coordinator/StoryCoordinator.swift
> +        var selectedDynamic: DynamicTypes
What you think about passing the player points to ChoiceViewInfosObject. Then, the model sets the dynamics variables. In that way, we avoid creating view logic in the Coordinator.

2020-11-26 11:28 UTC, pietro1704 approved these changes

2020-11-26 13:48 UTC, guilhermeShima approved these changes

2020-11-26 13:59 UTC, merged